# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments

# Site settings
title: "Andrew J Yale"
description: > # this means to ignore newlines until "email:"
   A blog about projects in all areas of tech

email: a.yale9@gmail.com
#blog logo
logo: "/assets/images/ajy_logo.jpg"
# blog cover
cover: "/assets/images/cover.jpg"

name: 'Andrew Yale'
author: 'Andrew Yale'
author_image: "/assets/images/author.jpg"

paginate:	5

#url: "http://myblog.***.***" # the base hostname & protocol for your site
#baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/andrewjyale
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="


  - icon:	github
    url:	https://github.com/yknot
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
