# Build settings
highlighter: rouge

# Site settings
title: "Andrew J Yale"
description: > # this means to ignore newlines until "email:"
   A blog about projects in all areas of tech

email: a.yale9@gmail.com
#blog logo
logo: "/assets/images/ajy_logo.jpg"
# blog cover
cover: "/assets/images/cover.jpg"

name: 'Andrew Yale'
author: 'Andrew Yale'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://yknot.github.com" # the base hostname & protocol for your site
#baseurl: ""

# fix template issue
exclude: [vendor]

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/andrewjyale
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon: instagram
    url: https://instagram.com/andrewjyale/
    desc: Follow me on instagram
    share_url:
    share_title:
    share_link:

  - icon:	github
    url:	https://github.com/yknot
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon: flickr
    url: https://www.flickr.com/photos/andrewjyale/
    desc: Check out my photos
    share_url:
    share_title:
    share_link:


# Google services
google_analytics: UA-84927624-1
